In [17]:
import pandas as pd
import numpy as np

In [31]:
data = pd.read_csv("gs://ukbb_spleen/CHIPCAD_pheno_v4.csv", sep='\s+')
data.head()

,ID,Filename,age.x,race.x,Sex.x,SmokingStatusv2.x,tchol.x,hdl.x,SBP.x,antihtnbase.x,...,CHIP_10,DNMT3A_10,non_DNMT3A_10,TET2_10,ASXL1_10,JAK2_10,PPM1D_10,TP53_10,SF3B1_10,SRSF2_10
0,1000107,1000107_20201_2_0.zip,49,white,Female,Previous,199.845320,61.059551,153.0,0,...,0,0,0,0,0,0,0,0,0,0
1,1000169,1000169_20201_2_0.zip,59,white,Female,Previous,239.211135,55.220417,130.0,0,...,0,0,0,0,0,0,0,0,0,0
2,1000336,1000336_20201_2_0.zip,42,white,Female,Current,203.750965,70.843000,118.0,0,...,0,0,0,0,0,0,0,0,0,0
3,1000387,1000387_20201_2_0.zip,64,white,Female,Never,268.174786,72.351121,153.0,0,...,0,0,0,0,0,0,0,0,0,0
4,1000408,1000408_20201_2_0.zip,56,white,Female,Never,242.459395,54.911059,113.0,0,...,0,0,0,0,0,0,0,0,0,0

In [19]:
mri_data = pd.read_csv("gs://ukbb_spleen/MRI_acquisition_times.csv", sep=',')
mri_data = mri_data.rename({'Unnamed: 0': 'ID', 'sex': 'Sex.x', 'enroll_age':'age.x'}, axis='columns')
mri_data['age.x'] = mri_data['age.x'].apply(np.floor).astype(int)
mri_data.head()

,ID,files,Sex.x,enroll_date,age.x,birthdate,acquisition_time,age_at_mri,predicted_age
0,1000107,/mnt/disks/mdrk-reingest-10tb/ukb_bulk/liver/i...,Female,2009-02-05,49,1959-11-15,2017-07-18,57.674011,52.849648
1,1000336,/mnt/disks/mdrk-reingest-10tb/ukb_bulk/liver/i...,Female,2008-08-19,42,1966-04-15,2019-10-19,53.512392,55.308680
2,1000387,/mnt/disks/mdrk-reingest-10tb/ukb_bulk/liver/i...,Female,2009-12-11,64,1945-01-15,2018-01-12,72.992601,76.734820
3,1000408,/mnt/disks/mdrk-reingest-10tb/ukb_bulk/liver/i...,Female,2008-07-19,56,1951-09-15,2019-12-01,68.212215,65.637375
4,1000426,/mnt/disks/mdrk-reingest-10tb/ukb_bulk/liver/i...,Female,2010-05-10,61,1948-05-15,2018-05-21,70.016496,64.323090

In [26]:
# make sure that the IDs match up
data.drop_duplicates('ID', inplace = True)
print(data.shape)
print(len(data.ID.unique()))

print(mri_data.shape)
print(len(mri_data.ID.unique()))

merged = data.merge(mri_data, on = ['ID', 'age.x', 'Sex.x'], how = 'inner')
print(merged.shape)
print(len(merged.ID.unique()))

(43543, 83)
43543
(43543, 83)
43543
(30183, 9)
30183
(30183, 9)
30183
(29150, 89)
29150

In [35]:
import pandas as pd
df=pd.read_csv("gs://ukbb_spleen/Abdominal_features/abdominal_features.csv")
#f.21083.2.0 and f.21083.3.0, use latter because more updated
df.head()

,f.eid,f.21080.2.0,f.21080.3.0,f.21081.2.0,f.21081.3.0,f.21082.2.0,f.21082.3.0,f.21083.2.0,f.21083.3.0,f.21084.2.0,...,f.23364.2.0,f.23364.2.1,f.23364.3.0,f.23364.3.1,f.24352.2.0,f.24352.3.0,f.24353.2.0,f.24353.3.0,f.24354.2.0,f.24354.3.0
0,1000015.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1000023.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1000037.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1000042.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1000059.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN