In [1]:
import pandas as pd

In [13]:
cols_to_use = ['FID', 'IID', 'original_gldm_LargeDependenceHighGrayLevelEmphasis', 'original_shape_Sphericity']

In [5]:
df = pd.read_csv('radiomics_spleen.csv')
df_new = df.drop_duplicates('ID').dropna()

/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3552: DtypeWarning: Columns (4,5,6,7,13) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [4]:
df_new.head()

,Unnamed: 0,Image,Mask,ID,original_shape_Elongation,original_shape_Flatness,original_shape_LeastAxisLength,original_shape_MajorAxisLength,original_shape_Maximum2DDiameterColumn,original_shape_Maximum2DDiameterRow,...,original_glszm_SmallAreaHighGrayLevelEmphasis,original_glszm_SmallAreaLowGrayLevelEmphasis,original_glszm_ZoneEntropy,original_glszm_ZonePercentage,original_glszm_ZoneVariance,original_ngtdm_Busyness,original_ngtdm_Coarseness,original_ngtdm_Complexity,original_ngtdm_Contrast,original_ngtdm_Strength
0,332opp.nii.gz,/home/jupyter/MRI-spleen/segments/2163449/1_op...,/home/jupyter/MRI-spleen/segments/2163449/1_se...,2163449,0.614754,0.543869,45.018282,82.774178,84.723078,99.478641,...,115.250148,0.004424,6.495345,0.044322,240991.235187,9.614468,0.000141,267.773907,0.012883,0.061435
2,331opp.nii.gz,/home/jupyter/MRI-spleen/segments/1663198/1_op...,/home/jupyter/MRI-spleen/segments/1663198/1_se...,1663198,0.591721,0.381217,34.800718,91.288546,90.801982,99.322706,...,106.695543,0.005587,6.604412,0.063252,175221.049222,9.385529,0.000135,338.442457,0.013411,0.065248
4,330opp.nii.gz,/home/jupyter/MRI-spleen/segments/2207595/1_op...,/home/jupyter/MRI-spleen/segments/2207595/1_se...,2207595,0.683953,0.459054,35.060439,76.375492,80.802228,86.608314,...,156.123062,0.004515,6.443623,0.088837,71921.65726,5.716505,0.000173,568.758928,0.021135,0.096755
6,329opp.nii.gz,/home/jupyter/MRI-spleen/segments/3310181/1_op...,/home/jupyter/MRI-spleen/segments/3310181/1_se...,3310181,0.585659,0.373912,31.835099,85.140533,77.87811,89.106678,...,140.722762,0.00547,6.667386,0.103035,60599.449308,6.040748,0.000166,608.023723,0.023323,0.094757
8,328opp.nii.gz,/home/jupyter/MRI-spleen/segments/2813366/1_op...,/home/jupyter/MRI-spleen/segments/2813366/1_se...,2813366,0.679241,0.492919,37.47275,76.022175,81.786307,90.873539,...,130.212519,0.005155,6.475245,0.067679,119609.295168,6.052803,0.000162,560.532495,0.010685,0.128646

In [14]:
df_new['FID'] = df_new.ID
df_new['IID'] = df_new.ID
gwas_pheno = df_new[cols_to_use]
print(gwas_pheno.shape)

(42772, 4)

In [16]:
gwas_pheno = gwas_pheno.rename(columns = {'original_gldm_LargeDependenceHighGrayLevelEmphasis': 'grayleveldependence', 'original_shape_Sphericity':'sphericity'})
gwas_pheno.head()

       FID      IID  grayleveldependence  sphericity
0  3254582  3254582         12317.900916    0.731904
2  1939825  1939825         15811.424214    0.708084
4  4945438  4945438         19793.744444    0.723825
6  1599847  1599847         15188.498501    0.705983
8  5687109  5687109         15487.982397    0.661646

In [17]:
gwas_pheno.to_csv('gwas_pheno_small_spleen.csv')