In [1]:
import pandas as pd

In [24]:
cols_to_use = ['FID', 'IID']
spleen_prev_cols = ['original_glszm_GrayLevelNonUniformity', 'original_glcm_Id', 'original_shape_Sphericity']
spleen_inc_cols = ['original_firstorder_Kurtosis', 'original_gldm_LargeDependenceHighGrayLevelEmphasis', 
                  'original_glszm_GrayLevelNonUniformity', 'original_glszm_SmallAreaLowGrayLevelEmphasis',
                   'original_shape_Maximum2DDiameterSlice']
spleen_col_map = {'original_glszm_GrayLevelNonUniformity': 'graynonuniform',
                  'original_glcm_Id': 'grayinversediff',
                  'original_shape_Sphericity':'sphericity',
                  'original_firstorder_Kurtosis':'kurtosis',
                  'original_gldm_LargeDependenceHighGrayLevelEmphasis': 'graydependence', 
                  'original_glszm_SmallAreaLowGrayLevelEmphasis': 'grayemphasis',
                  'original_shape_Maximum2DDiameterSlice': 'max2Ddiam',
                  }

In [25]:
df = pd.read_csv('radiomics_spleen.csv')
df_new = df.drop_duplicates('ID').dropna()

/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3552: DtypeWarning: Columns (4,5,6,7,13) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [20]:
df_new.head()

,Unnamed: 0,Image,Mask,ID,original_shape_Elongation,original_shape_Flatness,original_shape_LeastAxisLength,original_shape_MajorAxisLength,original_shape_Maximum2DDiameterColumn,original_shape_Maximum2DDiameterRow,...,original_glszm_SmallAreaHighGrayLevelEmphasis,original_glszm_SmallAreaLowGrayLevelEmphasis,original_glszm_ZoneEntropy,original_glszm_ZonePercentage,original_glszm_ZoneVariance,original_ngtdm_Busyness,original_ngtdm_Coarseness,original_ngtdm_Complexity,original_ngtdm_Contrast,original_ngtdm_Strength
0,238opp.nii.gz,/home/jupyter/MRI-spleen/segments/3254582/2_op...,/home/jupyter/MRI-spleen/segments/3254582/2_se...,3254582,0.583105,0.370172,14.449694,39.035049,40.311289,40.804412,...,47.836625,0.019258,5.949421,0.103474,8252.858176,2.420121,0.001311,180.687131,0.038700,0.191967
2,237opp.nii.gz,/home/jupyter/MRI-spleen/segments/1939825/2_op...,/home/jupyter/MRI-spleen/segments/1939825/2_se...,1939825,0.56453,0.401051,18.18216,45.336238,48.020829,42.379240,...,53.150024,0.018274,5.854841,0.098211,14176.627323,2.990630,0.000889,213.143306,0.030549,0.160346
4,236opp.nii.gz,/home/jupyter/MRI-spleen/segments/4945438/2_op...,/home/jupyter/MRI-spleen/segments/4945438/2_se...,4945438,0.548216,0.407604,18.855504,46.259408,44.102154,47.634021,...,69.031815,0.011349,5.820148,0.082296,20574.697206,3.251898,0.000810,175.820398,0.023089,0.151243
6,235opp.nii.gz,/home/jupyter/MRI-spleen/segments/1599847/2_op...,/home/jupyter/MRI-spleen/segments/1599847/2_se...,1599847,0.55668,0.365778,17.603708,48.126819,43.863424,55.470713,...,43.888020,0.016508,5.642847,0.061216,31155.281555,4.103885,0.000855,130.379893,0.014875,0.147738
8,234opp.nii.gz,/home/jupyter/MRI-spleen/segments/5687109/2_op...,/home/jupyter/MRI-spleen/segments/5687109/2_se...,5687109,0.469825,0.338312,13.945088,41.219605,38.078866,39.000000,...,68.921958,0.009265,6.017813,0.092707,7901.332407,1.380647,0.001681,218.155734,0.018914,0.409288

In [28]:
df_new['FID'] = df_new.ID
df_new['IID'] = df_new.ID
gwas_pheno = df_new[cols_to_use+spleen_prev_cols+spleen_inc_cols]
gwas_pheno = gwas_pheno.loc[:,~gwas_pheno.columns.duplicated()]
print(gwas_pheno.shape)

(42772, 9)

In [29]:
gwas_pheno = gwas_pheno.rename(columns = spleen_col_map)
gwas_pheno.head()

,FID,IID,graynonuniform,grayinversediff,sphericity,kurtosis,graydependence,grayemphasis,max2Ddiam
0,3254582,3254582,72.100606,0.561278,0.731904,4.583191,12317.900916,0.019258,24.413111
2,1939825,1939825,113.396469,0.578215,0.708084,4.369097,15811.424214,0.018274,31.384710
4,4945438,4945438,98.134113,0.613475,0.723825,5.284717,19793.744444,0.011349,29.966648
6,1599847,1599847,86.584229,0.657880,0.705983,4.327259,15188.498501,0.016508,32.062439
8,5687109,5687109,49.499096,0.587268,0.661646,5.299436,15487.982397,0.009265,23.323808

In [30]:
gwas_pheno.to_csv('gwas_pheno_spleen.csv')